[package]
name = "steadcopy-app"
description = "稳拷 steadcopy 桌面应用"
version = "0.1.0"
edition = "2021"
rust-version = "1.85"
license = "MIT"

[lib]
name = "steadcopy_app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
steadcopy-core = { path = "../../crates/steadcopy-core" }
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
time = { version = "0.3", features = ["formatting", "local-offset"] }
tauri-plugin-single-instance = "2.4.3"
tauri-plugin-notification = "2.3.3"
